### ISSUE TITLE
Does not work inside an AsciiDoc table cell

### ISSUE THREAD

**Issue by brunchboy** [Deep-Symmetry/asciidoctor-bytefield#2]
**Describe the bug**
Attempting to include a `bytefield` block in a table cell results in a run-time error.

**To Reproduce**
Set up a document with a table like this one:
```asciidoc
[options="header"]
|===
| Offset | Bitmask | Description

| Offset
a| [bytefield]
----
(draw-box 0xFF)
----
| Description

|===
```

**Expected behavior**
The cell includes the image.

**Observed result**
Rendering fails with `error: cell.innerDocument is not a function`

**Additional context**
@mojavelinux reports: it's a common mistake. the AsciiDoc table cell requires some special handling by the extension...and it's easy to forget.

**Comment by mojavelinux** [comment]
In theory, a block extension shouldn't have to be concerned with whether its in an AsciiDoc table cell. It could be a result of the block the extension is generating, or it could be an Asciidoctor version issue (an old bug coming back to haunt us). I'll need to study in more detail to understand what's happening.

**Comment by brunchboy** [comment]
Ok, thank you!

**Comment by brunchboy** [comment]
@Swiftb0y, David Jencks said on the asciidoctor/asciidoctor Gitter channel that he believed you and he had proven this was not actually a problem with the extension. Do you agree? Can I close this?

**Comment by mojavelinux** [comment]
I can verify this problem has nothing to do with this extension, and what's causing it is not present in the provided scenario. In other words, we can't reproduce it.

**Comment by brunchboy** [comment]
This turns out to have been a red herring: the problem was that asciidoctor-mathjax traverses the entire document tree, and can’t handle table nodes that are formatted as asciidoc.
